document.write("<div class=\"menu\">");
document.write("		<ul class=\"dmx l\">");
document.write("			<li>");
document.write("				<a href=\"https:\/\/old.musestar.cc\/\"><img src=\"https:\/\/old.musestar.cc\/favicon.ico\" width=\"25\" height=\"25\"><\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"https:\/\/old.musestar.cc\/\">首页<\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"https:\/\/old.musestar.cc\/animation\">缪斯星动漫<\/a><\/li>");
document.write("			<li class=\"nav\">");
document.write("				<a href=\"https:\/\/old.musestar.cc\/movie\">缪斯星影视<\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"http:\/\/www.musestars.top\">缪斯星搜索<\/a><\/li>");
document.write("    <\/ul>");
document.write("<ul class=\"dme r\">");
document.write("			<li>");
document.write("<a href=\"https:\/\/old.musestar.cc\/musestar\" >缪斯星官方<\/a>");
document.write("			<\/li>");
document.write("			<li>");
document.write("<a href=\"https:\/\/old.musestar.cc\/muse\" >缪斯星专区<\/a>");
document.write("			<\/li>");
document.write("			<li>");
document.write("<a href=\" \" >缪斯星暂无<\/a>");
document.write("			<\/li>");
document.write("    <\/div>");
document.write("	<br>");